name: Linux

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  TestLinux:
    name: Python ${{ matrix.python }} ${{ matrix.display_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # 2017
          - python: 3.6
            numpy: "1.13.*"
            sqlalchemy: "1.1.*"
            geoalchemy2: "0.4.*"
            pygeos: "0.5.*"
          # 2018
          - python: 3.7
            numpy: "1.15.*"
            sqlalchemy: "1.2.*"
            geoalchemy2: "0.5.*"
            pygeos: "0.7.*"
          # 2019
          - python: 3.8
            numpy: "1.17.*"
            sqlalchemy: "1.3.*"
            geoalchemy2: "0.6.*"
            pygeos: "0.8.*"
          # 2020
          - python: 3.9
            numpy: "1.19.*"
            sqlalchemy: "1.3.*"
            geoalchemy2: "0.7.*"
            pygeos: "0.9.*"
          # current
          - python: 3.9
            display_name: "latest"
            numpy: "1.*"
            sqlalchemy: "1.*"
            geoalchemy2: "0.8.*"
            pygeos: "0.*"
          # current - no optional deps
          - python: 3.9
            numpy: "1.*"
            sqlalchemy: "1.*"


    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install python dependencies
        shell: bash
        run: |
          pip install --disable-pip-version-check --upgrade pip setuptools wheel
          pip install pytest numpy==${{ matrix.numpy }} sqlalchemy==${{ matrix.sqlalchemy }}
          pip list

      - name: Run tests
        shell: bash
        run: |
          pytest
