name: Linux

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  TestLinux:
    name: Linux, Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # 2019
          - python: 3.7
            pins: "numpy==1.15.* sqlalchemy==1.3.* geoalchemy2==0.6.* shapely==2.0.*"
          # 2019
          - python: 3.8
            pins: "numpy==1.17.* sqlalchemy==1.3.* geoalchemy2==0.6.* shapely==2.0.*"
          # 2021
          - python: 3.9
            pins: "numpy==1.19.* sqlalchemy==1.3.* geoalchemy2==0.7.* shapely==2.0.*"
          # 2022
          - python: "3.10"
            pins: "numpy==1.21.* sqlalchemy==1.4.* geoalchemy2==0.8.* shapely==2.0.*"
          # current
          - python: "3.11"
            pins: "geoalchemy2 shapely"
          # current - no optional deps
          - python: "3.11"
            deps: ""

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install sqlite3 and spatialite libraries
        run: |
          sudo apt-get install --yes --no-install-recommends sqlite3 libsqlite3-mod-spatialite
  
      - name: Install python dependencies
        run: |
          pip install --disable-pip-version-check --upgrade pip setuptools
          pip install -e .[test] ${{ matrix.pins }}
          pip list

      - name: Run tests
        run: pytest --cov
